'use strict';

module.exports = {
	FACTS: [
		"Martin Luther King Jr. talked Nichelle Nichols (Lt. Uhura) out of leaving Star Trek: The Original Series.",
		"The popular line Beam me up, Scotty, was never said exactly in this way in the Star Trek series or film.",
		"An alternate juror for the 1996 Whitewater trial wore a Star Trek: The Next Generation uniform with a phaser and tricorder during the trial. She was later dismissed for talking to a journalist.",
		"Star Trek: TNG character Geordi La Forge was named after George La Forge, a devoted fan of the original Star Trek series. George La Forge had muscular dystrophy and died in 1975.",
		"Lucille Ball, from I Love Lucy and head of Star Trek’s parent company Desilu Productions, single handedly kept Star Trek: TOS from cancellation during the first season. The series was finally canceled in its third season, after 79 episodes. It then gained immense popularity in syndication.",
		"The original Star Trek series was originally marketed as Wagon Train to the Stars, after the popular 1957 western, Wagon Train.",
		"Star Trek: TOS aired from September 8, 1966, to September 2, 1969. The show was a way for its creator Eugene Wesley Gene Roddenbery (1921-1991) to comment on contemporary issues through the guise of science fiction.",
		"Scientists from the Jet Propulsion Laboratory wore Spock ears while monitoring the Mariner V on its October 1967 fly-by of Venus.",
		"Star Trek: TNG had the highest ratings of any Star Trek series.",
		"The popular 2009 Star Trek Reboot movie is the eleventh film in the Star Trek franchise. The film has earned high critical praise and has grossed more revenue than all previous Star Trek films.",
		"The Star Trek franchise includes six series: The Original Series, The Animated Series, The Next Generation, Deep Space Nine, Voyager, and Enterprise, totaling 726 episodes.",
		"Gene Roddenberry initially cast girlfriend (and later wife) Majel Barrett as Captain Pike’s Number One (first officer) in the series first pilot. NBC executives, however, demanded the character be cut because they said audience members could not relate to such a powerful woman character.",
		"Initially, NBC asked Gene Roddenberry to get rid of the guy with the pointy ears partly because they were worried about his satanic appearance. Luckily, Roddenberry refused to cut Spock.",
		"Most male Vulcan names begin with S and most females’ names with a T followed by an apostrophe.",
		"The BBC banned a TNG first-season episode titled Conspiracy because of the graphic phaser death of Star Fleet Inspector Dexter Remmick, who was a host to a disgusting mother creature. The BBC also did not air a 1990 TNG episode titled High Ground due to Data’s passing remark that Ireland would be reunified as a result of successful terrorist activities in 2024. BBC Two finally aired the episode in 2007.",
		"During the first season of TNG, Patrick Stewart had a sign over his door that read: Beware of Unknown Shakespearean Actor.",
		"DeForest Kelly (1920-1999) was the first of the three original members to appear on TNG. He was also the first original cast member of TOS to pass away.",
		"The Borg were initially conceptualized as being insects but took on their ultimate form due to budget restraints. The hive motif, however, remained.",
		"In the Star Trek universe, Zefram Cochrane developed faster-than-light warp drive around 2061 and conducted his test flight to Steppenwolf’s Magic Carpet Ride.",
		"On impulse drive, it would take 400,000 years for the Enterprise to cross the galaxy.",
		"Warp engines work by allowing particles of matter and antimatter to commingle in a reaction chamber regulated by a dilithium crystal. When the particles interact, they destroy each other, giving off enough energy to allow the ship to warp into space.",
		"The Enterprise usually can operate safety from warp drive 1 to 9.2. Traveling at warp 10, as seen in Star Trek: Voyager, mutates humans into big salamander creatures. However, in the final episode of the preceding series TNG, All Good Things, Federation starships traveled at warp 13.",
		"In TOS, uniform colors indicated the wearer’s role on the Enterprise. Gold uniforms indicated the wearer was on a command track. Blue meant the sciences, including medicine. Red indicated support services, such as communications, engineering, or security.",
		"The star dates Kirk mentions in his captain’s log each week in TOS are not based on our current Gregorian calendar dates. TOS star dates were largely arbitrary and were created just to let the audiences know the show took place in the future. Later Star Treks attempted to be more consistent with star dates.",
		"The episode titled Spock’s Brain ranks as one of the worst TOS episodes due to clichés and an implausible plot. The phrase Spock’s Brain has become a cultural term that refers to an unintentionally humorous television episode.",
		"The Enterprise in TOS is 953.7 feet long, which is more than the length of three football fields. The Enterprise-D in TNG is more than twice the length of Kirk’s ship at 2,103 feet. That’s as big as the Paramount Studio lot in Hollywood.",
		"The only official intoxicant served in TNG’s Ten-Forward is Synthenol, an artificial booze that loses its inebriating effects the moment a crew member leaves the bar.",
		"Red-shirting became a Star Trek slang word for an extra who was killed to demonstrate the danger the main characters were in. The extra almost always wore a red uniform. In tribute to the original series’ red-shirting, red-shirted Chief Engineer Olsen in Star Trek (2009) meets his death during an orbital skydive onto a drilling platform while Kirk and Sulu survive.",
		"Data’s cat Spot was initially a long-haired male but became a short-haired female later in the series. Data didn’t seem to notice.",
		"Although Roddenberry was actively involved in the Star Trek animated series’ conception and production, he did not consider them to be canon or part of the established history for the characters he created.",
		"Vulcans were once an extremely violent and emotional people until Surak developed a new philosophy of logic, which spawned the Vulcan Time of Awakening. Those opposed to Vulcan logic left the planet and founded colonies elsewhere, most notably the Romulan Star Empire.",
		"Vulcans were one of the first to develop warp drive, and they helped humans navigate the perils of warp travel. The official contact between Vulcans and humans occurred on April 5, 2063, when a Vulcan survey ship detected the warp flight of Captain Zefram Cochrane’s Phoenix.",
		"Vulcan’s have teeth that humans don’t have, such as anterior tricuspids. Their heart is where a human’s liver would normally be and beats several hundred times a minute. They have no appendix.",
		"Vulcans have inner eyelids that protect their eyes from the intensity of the Vulcan sun. They can also survive several days without water, perhaps because they evolved on a hot, dry planet.",
		"The Vulcan brain has been described as a puzzle wrapped in an enigma, housed inside a cranium.",
		"Besides the Trill, Vulcans are the only other known humanoid in the Star Trek universe who are able to transfer one individual’s consciousness into another’s (known as the mind meld).",
		"Lieutenant Uhura’s name means freedom in Swahili.",
		"Even though they’d prefer not to mate, Vulcans are compelled to reproduce by a ritual called Pon Farr. Once every seven years, they are consumed by Plak-tow, or blood fever, in which they become savage and may even fight to the death.",
		"Most Vulcans are vegetarians and do not touch food with their hands unless they are wearing special gloves.",
		"In an alternate reality established in the 2009 Star Trek film, Vulcan was destroyed by the Romulan Nero in 2258.",
		"When Spock sacrificed his own life to save the Enterprise from destruction at Kahn’s hand in the film The Wrath of Khan, Kirk could only say, Of all the souls I have encountered in my travels, his was the most . . . human.",
		"Dr. McCoy’s nickname Bones seems to come from two sources. First, it may have derived from the old-fashion colloquialism sawbones for a doctor. In Star Trek, Kirk calls McCoy Bones after McCoy reveals his divorce left him just his bones.",
		"Jeri Ryan, the actress who played Seven of Nine in Voyager turned down the role four times.",
		"James Doohan (Scotty) did not have a right middle finger. He lost it during WWII.",
		"Several famous actors and actresses have made guest appearances in Star Trek films and episodes, including Kim Cattrall, Kirstie Alley, Tom Bergeron, Jason Alexander, King Abdullah II of Jordan, Kelsey Grammer, Christopher Plummer, The Rock, Iman, Lee Meriwether, Joan Collins, Mick Fleetwood, Stephen Hawking, Ashley Judd, Famke Janssen, Mae Jemison, and Tom Morello.",
		"Actress Majel Barrett Roddenberry is the only actor to be in all Star Trek incarnations, including the animated series and films. Before her death in December 2008, she completed the voice of the computer in Star Trek.",
		"Star Trek is the first time Uhura has been given a name on screen, Nyota, though she is referred to as Nyota in the DC comics’ Who’s Who in Star Trek.",
		"Leonord Nimoy created the famous Spock neck pinch during the episode The Enemy Within when Spock was supposed to hit the evil Kirk over the head with the butt of a phaser. Nimoy wanted something more interesting and came up with an answer from within Spock’s hand-orientated background.",
		"At the same time the Star Trek series was beginning to create a loyal following, the Monkees were exploding onto TV sets. Consequently, Roddenberry created the character of Pavel Andreievich Chekhov as a close approximation of the Monkees’ lead singer, Davy Jones—with a Russian accent.",
		"Spock was originally conceived as a red-skinned alien with a plate in the middle of his stomach. He didn’t eat or drink but fed upon any form of energy that struck his stomach plate.",
		"An October 1967 TV Guide ad by RCA cited Star Trek: TOS as the reason to buy a color TV.",
		"Geordie La Forge’s VISOR (Visual Instrument and Sensory Organ Replacement) was actually based on a hair clip. LaVar Burton describes wearing the VISOR as a living hell as it gave him headaches and reduced his vision.",
		"Nimoy and Shatner are the only two actors to appear in every episode of the original Star Trek series.",
		"DeForest Kelley (Dr. McCoy) was originally offered the role of Spock.",
		"The U.S.S. Enterprise NCC-1701 from the original series has a crew complement of 430 men and women. The Enterprise NCC 1701-D from TNG has a crew complement of 1,012 men, women, and children, reflecting a more family-friendly and less warlike atmosphere than TOS.",
		"The Enterprise was initially a French sailing ship in 1671. A later ship was captured by the British royal navy in 1705 and renamed HMS Enterprise. The first Earth Starfleet vessel, commissioned Enterprise NX-01, launched in 2151 under the command of Captain Jonathan Archer (of the Star Trek: Enterprise series).",
		"Divorce Klingon style means slapping your spouse, reciting the words N’Gos tlhogh cha! (our marriage is done) and spitting in your spouse’s face.",
		"In the Klingon creation myth, Adam and Eve destroyed their gods and turned the heaven into ashes.",
		"Although Voyager was initially allotted only two shuttlecrafts, over the course of seven years, they went through dozens.",
		"Despite Picard’s British accent, he was born in France where his family owned a vineyard.",
		"Riker was born in Valdez, Alaska, and his mother died when he was two years old. His father was a civilian strategist who worked for Starfleet and essentially left Will on his own when he was 15 years old.",
		"Klingons prefer to eat food that’s still alive. A favorite Klingon meal is gagh, a slimy serpent-worm dish, followed by warm blood wine.",
		"A Romulan Warbird is nearly twice the length of the Enterprise in TNG and is powered by an artificial quantum singularity or a black hole.",
		"Captain Archer from Enterprise owns a dog named Porthos, a character in the novel The Three Musketeers by Alexandre Dumas. His litter mates were named after the two other Musketeers.",
		"Captain Kirk was born on Earth in Iowa. He is paradox in many ways—for example, he depends on technology but likes resolving conflict with a hands-on approach, and he deplores humankind’s violence but has a distrust of apparent peace. Additionally, although he has a reputation as a lady’s man, no woman has come between him and his career—or his ship.",
		"Spock was the first Vulcan to enlist in Starfleet. His father did not speak to him for 18 years because he opted to join Starfleet rather than attend the Vulcan Science Academy.",
		"The sign Spock makes for Live long and prosper is actually half of what is commonly done by the Cohanim Jewish priests when they bless the congregation. Both Nimoy and Shatner are from Jewish descent, and both are mentioned in Adam Sandler’s Hanukkah song.",
		"Spock’s fiancée, T’Pring, spurned him at the altar in favor of a more traditional Vulcan.",
		"The Enterprise’s Jefferies Tubes (small corridors or tunnels that provide access to critical starship systems) were named after Matt Jeffries, the TOS art director, who designed the original starship Enterprise.",
		"Art Director Matt Jeffries (1921-2003) was a bomber pilot during WWII and based the Enterprise’s identifying letters NCC on twentieth-century aircraft registration codes. For example, the N represents an aircraft registered in the United States, and the first C represents a civil aircraft. Jeffries added a second C because he thought it looked neat. In the Star Trek universe, NCC stands for Naval Construct Contract and USS stands for United Space Ship (not United States Ship).",
		"Randy Pausch—Carnegie Mellon computer science professor, author of the Last Lecture, and devoted Star Trek fan—appeared in the 2009 movie Star Trek. He died on July 25, 2008, of pancreatic cancer.",
		"Star Trek (2009) director J.J. Abrams glued Zachary Quinto’s (Spock’s) fingers together so he could perfect the Vulcan salute.",
		"Star Trek 2009 is dedicated to Gene Roddenberry and his wife Majel Barrett.",
		"According to Spock’s mother, Amanda, humans cannot pronounce Spock’s full name. It is written as S’chn-T Gai Spock, son of S’chn-T gai Sarek (of Skon and Solkar) of Vulcan.",
		"Shatner’s first wife left him after Star Trek: The Original Series was canceled.",
		"Shatner’s favorite episode is The Devil in the Dark because he says it contains all the elements that made Star Trek successful: intelligence and excitement.",
		"Captain Kirk’s dramatic pauses in speech have been called The Shatnerian.",
		"Fans of Star Trek have been called Trekologists, Treksters, Trekkies, and Trekkers. Some Star Trek fans prefer to be called Trekkers rather than Trekkies, though there is considerable debate about what the differences are between the terms.",
		"Roddenberry said Star Trek was influenced by A.E. van Vogt’s novel The Voyage of the Space Beagle, Eric Frank Russell’s Marathon series, Jonathan Swift’s Gulliver’s Travels, C. S. Forester’s Horatio Hornblower, and the film The Forbidden Planet.",
		"The original Star Trek concept included Captain April of the S.S. Yorktown, who later was reconceptualized as Captain Christopher Pike during the first pilot. After the first pilot was canceled, Captain Kirk replaced Pike.",
		"Hikaru Sulu was initially cast as the ship’s physicist before being cast as helmsman for the rest of the series.",
		"The number 47 seems to make recurrent appearances in Star Trek starting with the TNG. Apparently writer Joe Menosky, who attended Pomona College, heard that all numbers are equal to 47.",
		"Ferengi, the name of an alien race, is the Persian word for foreigner.",
		"In the Voyager episode Deadlock, the doctor has to deliver a baby of a human mother and Ktarian father. The baby has spiky ridges on its forehead arranged in such a way that it would have lacerated the mother’s uterus and vagina if the doctor had not been able to manage the delivery by transporter beam.",
		"Writers considered several other titles before deciding on Star Trek: The Next Generation, including Star Trek: Future Trek, Star Trek: Enterprise VII, and Star Trek: A New Generation.",
		"George Takei once urged Star Trek and Star Wars fans to end their rivalry to unite their hatred against the Twilight movies."
	]
};
